name: Meta Triton TLX Tests
on:
  push:
    branches:
      - main

jobs:
  h100-tlx-test:
    if: github.repository_owner == 'facebookexperimental'
    runs-on: [linux.gcp.h100]
    timeout-minutes: 240
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tune Nvidia GPU
        run: |
          sudo nvidia-smi -pm 1
          sudo ldconfig
          nvidia-smi

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
